package com.main

import com.project.cinema.dto.*;
import java.util.List;
import java.util.Set;
import java.util.Date;
import com.project.cinema.helpers.Utility


rule "Regular Guest"
	agenda-group "regular_guest"
	no-loop true
    when
        $u: RegisteredUserDTO($ts: tickets)
        $reservation: TicketsDTO($id: movie.getId())
        accumulate(
			TicketsDTO($t: this, $movie : movie) from $ts,         	
			
         	$rezervacije: collectList($t),
         	$movies: collectList($movie)
         )
         Number($value: intValue >= 3) from accumulate(
        	MovieDTO($s: this, $id == $s.getId()) from $movies,
        	count($s)
        )
       
      
       eval($value >= 3 && $rezervacije.size()>=3)
    then
    	modify($reservation){
    		addPrivilege("REGULAR_GUEST");
    	}
    	System.out.println("Stalni posetilac" );
end

